services:
  # 서비스 이름
  mysql:
    # 이미지 버전
    image: mysql:8.0
    # 컨테이너 이름
    container_name: nestjs-boilerplate-mysql2
    # 재시작 정책
    restart: always
    # ENV FILE
    env_file:
      - ./.env
    # 환경 변수
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    ports:
      - '3306:3306'
